#!/usr/bin/env node
// Copies what the site needs from the rest of the repo into web/, so the app deploys on its own
// (`vercel deploy` from web/): the SDK source, the deployed addresses, the fitted countries, and the
// historical replay the "lights" section draws. Run before dev and build; the copies are committed
// and must not be edited by hand.
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const web = join(dirname(fileURLToPath(import.meta.url)), '..');
const repo = join(web, '..');
const HEADER = '// Generated by web/scripts/sync.mjs from sdk/ts/src. Do not edit here.\n';

// On Vercel only web/ is uploaded: the committed copies are used as they are.
if (!existsSync(join(repo, 'sdk/ts/src'))) {
  console.log('sync: repo sources not present (deploy build); using the committed copies');
  process.exit(0);
}
mkdirSync(join(web, 'src/sdk'), { recursive: true });
for (const f of readdirSync(join(repo, 'sdk/ts/src'))) {
  if (!f.endsWith('.ts')) continue;
  const src = readFileSync(join(repo, 'sdk/ts/src', f), 'utf8');
  writeFileSync(join(web, 'src/sdk', f), HEADER + src);
}

const dep = JSON.parse(readFileSync(join(repo, 'config/deployment.json'), 'utf8'));
const keep = ['chainId', 'deployer', 'usdg', 'actuary', 'actuaryVersion', 'pool', 'treasury', 'lifeRegistry', 'attestedIdentity', 'attester', 'timelock', 'market', 'countries', 'governance', 'sealed', 'retired', 'deployBlock'];
writeFileSync(join(web, 'src/sdk/deployment.json'), JSON.stringify(Object.fromEntries(keep.filter((k) => k in dep).map((k) => [k, dep[k]])), null, 1) + '\n');

// The historical replay (runs/replay.json): the 1965 cohort, trimmed to what the scene draws.
const runs = [process.env.TONTI_RUNS, '/media/dflame/UNIQ/arbit/runs', join(repo, 'runs')].find((p) => p && existsSync(join(p, 'replay.json')));
if (runs) {
  const r = JSON.parse(readFileSync(join(runs, 'replay.json'), 'utf8'));
  const out = { setup: r.setup, cohorts: {} };
  for (const y of ['1965', '1973', '2000']) {
    const c = r[y]?.cohort;
    if (!c) continue;
    out.cohorts[y] = {
      alive: c.alive,
      income_real: c.income_real.map((v) => Math.round(v)),
      shadow_runout_year: c.shadow_runout_year,
      shadow_alive_share: c.shadow_alive_share,
      rule4_runout_year: c.rule4_runout_year,
      rule4_alive_share: c.rule4_alive_share,
      min_real_income_100_alive: c.min_real_income_100_alive,
    };
  }
  mkdirSync(join(web, 'public/data'), { recursive: true });
  writeFileSync(join(web, 'public/data/replay.json'), JSON.stringify(out));
}
for (const f of ['personas-live.json', 'mainnet-quote.json', 'gas.json', 'mortality-validation.json', 'fairness-100.json', 'fairness-10000.json', 'ghost-detector.json', 'mutations-pool.json', 'mutations-registry.json']) {
  if (runs && existsSync(join(runs, f))) copyFileSync(join(runs, f), join(web, 'src/sdk', f));
}
console.log('synced sdk, deployment and data');
