// Generated by web/scripts/sync.mjs from sdk/ts/src. Do not edit here.
import { defineChain } from 'viem';

/** Robinhood Chain mainnet (an Arbitrum Orbit chain settling to Ethereum). */
export const robinhood = defineChain({
  id: 4663,
  name: 'Robinhood Chain',
  nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  rpcUrls: { default: { http: ['https://rpc.mainnet.chain.robinhood.com'] } },
  blockExplorers: { default: { name: 'Blockscout', url: 'https://robinhoodchain.blockscout.com' } },
  contracts: { multicall3: { address: '0xcA11bde05977b3631167028862bE2a173976CA11' } },
});

export const MULTICALL3 = '0xcA11bde05977b3631167028862bE2a173976CA11' as const;
