// Generated by web/scripts/sync.mjs from sdk/ts/src. Do not edit here.
// Generated by sdk/gen.py from config/mortality.json. Do not edit.
/** Countries the Actuary prices (both sexes), with the birth years fitted. */
export const countries = [
  {
    "iso3": "BGD",
    "isoNumeric": 50,
    "name": "Bangladesh",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "CHN",
    "isoNumeric": 156,
    "name": "China",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "IDN",
    "isoNumeric": 360,
    "name": "Indonesia",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "IND",
    "isoNumeric": 356,
    "name": "India",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "LKA",
    "isoNumeric": 144,
    "name": "Sri Lanka",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "MMR",
    "isoNumeric": 104,
    "name": "Myanmar",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "MYS",
    "isoNumeric": 458,
    "name": "Malaysia",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "NPL",
    "isoNumeric": 524,
    "name": "Nepal",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "PHL",
    "isoNumeric": 608,
    "name": "Philippines",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "SGP",
    "isoNumeric": 702,
    "name": "Singapore",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "THA",
    "isoNumeric": 764,
    "name": "Thailand",
    "birthYears": [
      1935,
      2005
    ]
  },
  {
    "iso3": "VNM",
    "isoNumeric": 704,
    "name": "Viet Nam",
    "birthYears": [
      1935,
      2005
    ]
  }
] as const;
