// Generated by web/scripts/sync.mjs from sdk/ts/src. Do not edit here.
import { type Address, type Client, type Hex, encodeFunctionData } from 'viem';
import { multicall, readContract } from 'viem/actions';
import { actuaryAbi } from './abi.ts';
import { MULTICALL3 } from './chain.ts';
import { type Iso3, type Sex, ageAt, cohortKey, fromUsdg, fromWad, toUsdg, toWad, yearAt } from './units.ts';

// The Actuary's reads on their own, so a page that only quotes loads only the Actuary's ABI (the
// full client in client.ts wraps these).

export type QuoteInput = {
  country: Iso3;
  sex: Sex;
  birthYear: number;
  /** Age income starts: 50–80, as the pool allows (the Actuary refuses anything else). */
  startAge: number;
  /** Dollars paid in now, and every month until the start age. */
  lumpSum?: number;
  monthly?: number;
  escalating?: boolean;
  /** Market paths, at most 512 (9.5M gas, 30% of the per-call cap). */
  paths?: number;
  /** The quote's clock. Pass a fixed time (say, today at 00:00 UTC) so identical inputs give an
   * identical quote: the Monte Carlo seed mixes in the age and year. */
  now?: Date;
};
export type Percentiles = { p10: number; p50: number; p90: number };
export type Quote = {
  /** Monthly income, dollars, after the pool's 0.30% a year fee. */
  incomeStart: Percentiles;
  incomeAt85: Percentiles;
  /** Median age the same starting income, drawn alone from the same pot, runs out. */
  soloRunoutAge: number;
  /** Chance of still being alive when it does. */
  soloOutliveProbability: number;
  /** The exact call, so anyone can re-run it (`cast call` or any RPC), and its raw result. */
  call: { to: Address; data: Hex };
  raw: readonly bigint[];
};

const percentiles = (v: readonly bigint[]): Percentiles => ({ p10: fromUsdg(v[0]), p50: fromUsdg(v[1]), p90: fromUsdg(v[2]) });

/** The on-chain quote: the Actuary's Monte Carlo, run by an eth_call (no gas paid). */
export async function quote(client: Client, actuary: Address, q: QuoteInput): Promise<Quote> {
  const now = q.now ?? new Date();
  const args = [
    cohortKey(q.country, q.sex, q.birthYear),
    toWad(ageAt(q.birthYear, now)),
    toWad(yearAt(now)),
    toWad(q.startAge),
    toUsdg(q.lumpSum ?? 0),
    toUsdg(q.monthly ?? 0),
    q.paths ?? 512,
    q.escalating ?? false,
  ] as const;
  const r = await readContract(client, { address: actuary, abi: actuaryAbi, functionName: 'quote', args });
  return {
    incomeStart: percentiles([r[0], r[1], r[2]]),
    incomeAt85: percentiles([r[3], r[4], r[5]]),
    soloRunoutAge: fromWad(r[6]),
    soloOutliveProbability: fromWad(r[7]),
    call: { to: actuary, data: encodeFunctionData({ abi: actuaryAbi, functionName: 'quote', args }) },
    raw: r,
  };
}

/** The cohort's chance of being alive at each whole age from `fromAge` to 100, from the
 * Actuary's own mortality (one Multicall3 eth_call of monthly death probabilities). */
export async function survival(client: Client, actuary: Address, country: Iso3, sex: Sex, birthYear: number, fromAge: number): Promise<{ age: number; alive: number }[]> {
  const key = cohortKey(country, sex, birthYear);
  const first = Math.ceil(fromAge);
  const ages = Array.from({ length: Math.max(0, 100 - first) }, (_, i) => first + i);
  const q = await multicall(client, {
    multicallAddress: MULTICALL3,
    allowFailure: false,
    contracts: ages.map((a) => ({ address: actuary, abi: actuaryAbi, functionName: 'qMonth', args: [key, toWad(a + 0.5), toWad(birthYear + a + 1)] }) as const),
  });
  let alive = 1;
  const out = [{ age: first, alive }];
  q.forEach((qm, i) => {
    alive *= (1 - fromWad(qm as bigint)) ** 12;
    out.push({ age: ages[i] + 1, alive });
  });
  return out;
}
