// Generated by web/scripts/sync.mjs from sdk/ts/src. Do not edit here.
import { countries } from './countries.ts';

/** The contracts' units: ages, years and probabilities are WAD (1e18); USDG has 6 decimals. */
export const WAD = 10n ** 18n;
export const USDG = 10n ** 6n;
const YEAR_SECONDS = 31_557_600; // Julian year, as the pool counts it

export type Sex = 'female' | 'male';
export type Iso3 = (typeof countries)[number]['iso3'];

/** A cohort's mortality key: (isoNumeric·2 + sex)·10000 + birthYear, sex 0 = female. */
export function cohortKey(country: Iso3, sex: Sex, birthYear: number): bigint {
  const c = countries.find((x) => x.iso3 === country);
  if (!c) throw new Error(`no mortality fitted for ${country}`);
  if (!Number.isInteger(birthYear) || birthYear < c.birthYears[0] || birthYear > c.birthYears[1]) {
    throw new Error(`${country} is fitted for births ${c.birthYears[0]}–${c.birthYears[1]}, not ${birthYear}`);
  }
  return BigInt((c.isoNumeric * 2 + (sex === 'male' ? 1 : 0)) * 10_000 + birthYear);
}

/** A decimal number of years (or any WAD quantity) as WAD, exactly for up to 9 decimals. */
export function toWad(x: number): bigint {
  const [int, frac = ''] = x.toFixed(9).split('.');
  return BigInt(int) * WAD + BigInt(frac.padEnd(18, '0'));
}

export function fromWad(x: bigint): number {
  return Number(x) / 1e18;
}

/** Dollars (USDG) as 6-decimal base units, rounded to the cent's hundredth. */
export function toUsdg(dollars: number): bigint {
  if (!(dollars >= 0)) throw new Error(`bad amount ${dollars}`);
  return BigInt(Math.round(dollars * 1e6));
}

export function fromUsdg(x: bigint): number {
  return Number(x) / 1e6;
}

/** The calendar year as the pool computes it: 1970 + seconds / Julian year. */
export function yearAt(date: Date): number {
  return 1970 + date.getTime() / 1000 / YEAR_SECONDS;
}

/** Age the way the pool computes it: now minus mid-year of birth. */
export function ageAt(birthYear: number, date: Date): number {
  return yearAt(date) - (birthYear + 0.5);
}
