#!/usr/bin/env python3
"""Regenerates the SDK's ABIs from the contracts themselves, so the frontend can't drift from them.

  python3 sdk/gen.py

Stylus contracts: `cargo stylus export-abi` (functions and errors), plus the events declared in
the Rust `sol!` blocks, compiled by Foundry into JSON. Solidity contracts: `forge inspect`.
Writes sdk/abi/<Contract>.json and sdk/ts/src/abi.ts (`as const`, for viem's type inference).
"""
import json
import os
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
import sys as _sys
_sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parents[1] / 'actuarial'))
from paths import target_dir  # noqa: E402
ENV = {**os.environ, 'CARGO_TARGET_DIR': str(target_dir()), 'CARGO_INCREMENTAL': '0'}
GEN = ROOT / 'contracts' / 'src' / 'generated'
STYLUS = {'Actuary': 'actuary-stylus', 'TontiPool': 'pool-stylus'}
SOLIDITY = ['Treasury', 'LifeRegistry', 'AttestedIdentity']


def stylus_interface(name, crate):
    sol = subprocess.run(['cargo', 'stylus', 'export-abi'], cwd=ROOT / 'engine' / crate, env=ENV,
                         capture_output=True, text=True, check=True).stdout
    src = (ROOT / 'engine' / crate / 'src' / 'lib.rs').read_text()
    # Only the contract's own events: stop at the test module (not at any #[cfg(test)] item).
    cut = src.find('#[cfg(test)]\nmod tests')
    src = src[:cut] if cut >= 0 else src
    events = sorted(set(m.group(0) for m in re.finditer(r'event \w+\([^)]*\);', src)))
    body = sol[:sol.rindex('}')] + ''.join(f'\n    {e}\n' for e in events) + '}\n'
    return body


def main():
    GEN.mkdir(exist_ok=True)
    for name, crate in STYLUS.items():
        (GEN / f'I{name}.sol').write_text(stylus_interface(name, crate))
    out = {}
    for name in STYLUS:
        target = f'src/generated/I{name}.sol:I{name}'
        out[name] = json.loads(subprocess.run(['forge', 'inspect', target, 'abi', '--json'], cwd=ROOT / 'contracts',
                                              capture_output=True, text=True, check=True).stdout)
    for name in SOLIDITY:
        out[name] = json.loads(subprocess.run(['forge', 'inspect', name, 'abi', '--json'], cwd=ROOT / 'contracts',
                                              capture_output=True, text=True, check=True).stdout)
    abi_dir = ROOT / 'sdk' / 'abi'
    abi_dir.mkdir(exist_ok=True)
    ts = ['// Generated by sdk/gen.py from the contracts. Do not edit.\n']
    for name, abi in out.items():
        (abi_dir / f'{name}.json').write_text(json.dumps(abi, indent=1) + '\n')
        ts.append(f'export const {name[0].lower() + name[1:]}Abi = {json.dumps(abi)} as const;\n')
        kinds = {k: sum(1 for x in abi if x['type'] == k) for k in ('function', 'event', 'error')}
        print(f'{name}: {kinds}')
    (ROOT / 'sdk' / 'ts' / 'src').mkdir(parents=True, exist_ok=True)
    (ROOT / 'sdk' / 'ts' / 'src' / 'abi.ts').write_text('\n'.join(ts))
    for f in abi_dir.glob('*.sol'):
        f.unlink()
    countries()


NAMES = {'BGD': 'Bangladesh', 'CHN': 'China', 'IDN': 'Indonesia', 'IND': 'India', 'LKA': 'Sri Lanka', 'MMR': 'Myanmar',
         'MYS': 'Malaysia', 'NPL': 'Nepal', 'PAK': 'Pakistan', 'PHL': 'Philippines', 'SGP': 'Singapore', 'THA': 'Thailand',
         'VNM': 'Viet Nam', 'USA': 'United States'}


def countries():
    """The cohorts the Actuary can price: every country with fitted mortality, and its birth years."""
    params = json.loads((ROOT / 'config' / 'mortality.json').read_text())['params']
    found = {}
    for v in params.values():
        found.setdefault((v['iso3'], v['isoNumeric']), set()).add(v['birthYear'])
    rows = [{'iso3': iso3, 'isoNumeric': num, 'name': NAMES.get(iso3, iso3), 'birthYears': [min(ys), max(ys)]}
            for (iso3, num), ys in sorted(found.items())]
    (ROOT / 'sdk' / 'ts' / 'src' / 'countries.ts').write_text(
        '// Generated by sdk/gen.py from config/mortality.json. Do not edit.\n'
        '/** Countries the Actuary prices (both sexes), with the birth years fitted. */\n'
        f'export const countries = {json.dumps(rows, indent=2)} as const;\n')
    print(f'countries: {len(rows)}')


if __name__ == '__main__':
    main()
